# Generated by Django 3.2.20 on 2023-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('12:00 for Lunch', 'Lunch Time'), ('18:00 for Dinner', 'Dinner Time')], max_length=20),
        ),
    ]
