# Generated by Django 3.2.20 on 2023-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_party_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='party_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
